export default {
	CHANGE_ANOMALY: 'CHANGE_ANOMALY',
	CHANGE_CALENDAR_MONTH: 'CHANGE_CALENDAR_MONTH',
	CHANGE_DATE: 'CHANGE_DATE',
	CHANGE_DEPTH: 'CHANGE_DEPTH',
	CHANGE_DROPDOWN_CALENDAR_MONTH: 'CHANGE_DROPDOWN_CALENDAR_MONTH',
	CHANGE_SOURCE: 'CHANGE_SOURCE',
	CHANGE_VERTEX_TYPE: 'CHANGE_VERTEX_TYPE',
	CHANGE_TIMEINTERVAL: 'CHANGE_TIMEINTERVAL',
	CHANGE_VIEW: 'CHANGE_VIEW',
	CLOSE_DOCUMENTS_BOX: 'CLOSE_DOCUMENTS_BOX',
	CLOSE_ERROR_BAR: 'CLOSE_ERROR_BAR',
	OPEN_NODE_DOCUMENTS: 'OPEN_NODE_DOCUMENTS',
	OPEN_NODE_SUBINTERVAL_DOCUMENTS: 'OPEN_NODE_SUBINTERVAL_DOCUMENTS',

	REQUEST_CALENDAR_DATA: 'REQUEST_CALENDAR_DATA',
	REQUEST_CALENDAR_DATA_SUCCEEDED: 'REQUEST_CALENDAR_DATA_SUCCEEDED',
	REQUEST_CALENDAR_DATA_FAILED: 'REQUEST_CALENDAR_DATA_FAILED',

	REQUEST_CONTEXT_DATA: 'REQUEST_CONTEXT_DATA',
	REQUEST_CONTEXT_DATA_SUCCEEDED: 'REQUEST_CONTEXT_DATA_SUCCEEDED',
	REQUEST_CONTEXT_DATA_FAILED: 'REQUEST_CONTEXT_DATA_FAILED',

	REQUEST_CONTEXT_DATA_FROM_CALENDAR_SUCCEEDED: 'REQUEST_CONTEXT_DATA_FROM_CALENDAR_SUCCEEDED',
	REQUEST_CONTEXT_DATA_FROM_CALENDAR_FAILED: 'REQUEST_CONTEXT_DATA_FROM_CALENDAR_FAILED',

	SEE_NODE_IN_CONTEXT: 'SEE_NODE_IN_CONTEXT',
	SELECT_DAY_ON_CALENDAR: 'SELECT_DAY_ON_CALENDAR',
	SELECT_NODE_ON_STREAMGRAPH: 'SELECT_NODE_ON_STREAMGRAPH',
	SELECT_SUB_INTERVAL: 'SELECT_SUB_INTERVAL',
	TOGGLE_ANOMALY_DROPDOWN: 'TOGGLE_ANOMALY_DROPDOWN',
	TOGGLE_SOURCE_DROPDOWN: 'TOGGLE_SOURCE_DROPDOWN',
	TOGGLE_DATE_DROPDOWN: 'TOGGLE_DATE_DROPDOWN',
	TOGGLE_TIMEINTERVAL_DROPDOWN: 'TOGGLE_TIMEINTERVAL_DROPDOWN',
	TOGGLE_SOURCE_ON_CALENDAR: 'TOGGLE_SOURCE_ON_CALENDAR'
};
